# Generated by Django 3.2.4 on 2021-06-27 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id tipo de usuario')),
                ('nombreTipoUsuario', models.CharField(max_length=50, verbose_name='Nombre tipo de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rutColaborador', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='rut de colaborador')),
                ('fotografiaColaborador', models.CharField(max_length=20, verbose_name='Fotografía colaborador')),
                ('nombrecompletoColaborador', models.CharField(max_length=40, verbose_name='Nombre completo de colaborador')),
                ('telefonoColaborador', models.IntegerField(verbose_name='Teléfono de colaborador')),
                ('direccionColaborador', models.CharField(max_length=30, verbose_name='Dirección de colaborador')),
                ('emailColaborador', models.CharField(max_length=20, verbose_name='Email de colaborador')),
                ('paisColaborador', models.CharField(max_length=15, verbose_name='País de colaborador')),
                ('constraseñaColaborador', models.CharField(max_length=8, verbose_name='Contraseña de colaborador')),
                ('tipousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ETJuan.tipousuario')),
            ],
        ),
    ]
